spring.application.name: config-server
server.port: 1017


spring.cloud.config.server.git.uri: https://github.com/tenneling/springcloud-config-server.git
spring.cloud.config.server.git.searchPaths: resources
spring.cloud.config.label: master
spring.cloud.config.server.git.username: tenneling@163.com
spring.cloud.config.server.git.password: yxms1314
